service: website-snapshot

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  stage: production

functions:
  snapshot: 
    handler: ./src/handler.snapshot
    timeout: 30
    events: # All events associated with this function (will create the aws gateway endpoint automagically)
      - http:
          path: snapshot
          method: get
